name: 'Run Iter8 Load Test'
description: 'Run an Iter8 load test experiment'
inputs:
  url:
    description: 'Application endpoint'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.url }}
