name: Test load-test action

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: test load-test action
    runs-on: ubuntu-latest
    steps:

    # Build new version as docker image and push to registry
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: run httpbin
      run: |
        set -e
        docker pull kennethreitz/httpbin
        docker run -p 80:80 kennethreitz/httpbin &
        while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://127.0.0.1/get)" != "200" ]]; do
          sleep 5; 
        done;

    # - name: Prepare values.yaml file
    #   run: |
    #     cat << EOF > values.yaml
    #       url: http://127.0.0.1/get
    #       SLOs:
    #         error-rate: 0
    #         latency-mean: 100
    #     EOF
    #     cat values.yaml

    # - name: Run load test
    #   uses: ./load-test
    #   with:
    #     # chart: load-test-http
    #     valuesFile: ../values.yaml
    #     logLevel: trace

    - name: install Iter8 CLI
      uses: iter8-tools/iter8@refs/pull/1224/merge
    - name: version
      run: | 
        iter8 version
    - name: launch
      run: |
        iter8 launch -c load-test-http --noDownload \
        --set url="http://$HOST_IP/get"
    - name: assert
      run: |
        iter8 assert -c completed -c nofailure

